apiVersion: v1
data:
  consul-template-config.hcl: "vault {\n  renew_token = true\n  vault_agent_token_file
    = \"/home/vault/.vault-token\"\n  retry {\n    backoff = \"1s\"\n  }\n}\n\ntemplate
    {\n  destination = \"/etc/secrets/vault.html\"\n  contents = <<EOH\n  <html>\n
    \ <body>\n  <p>Some secrets:</p>\n  {{- with secret \"secret/myapp/config\" }}\n
    \ <ul>\n  <li><pre>username: {{ .Data.username }}</pre></li>\n  <li><pre>password:
    {{ .Data.password }}</pre></li>\n  </ul>\n  {{ end }}\n  </body>\n  </html>  \n
    \ EOH\n}\n"
  vault-agent-config.hcl: |
    # Uncomment this to have Agent run once (e.g. when running as an initContainer)
    exit_after_auth = false
    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "agent-role"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }
kind: ConfigMap
metadata:
  name: vault-agent-config-g9cmfhmgmh
---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kustomize-test
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-test
  name: kustomize-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-test
  template:
    metadata:
      labels:
        app: kustomize-test
    spec:
      containers:
      - args:
        - agent
        - -config=/etc/vault/vault-agent-config.hcl
        - -log-level=debug
        env:
        - name: VAULT_ADDR
          value: https://35.222.149.11:443
        - name: VAULT_CACERT
          value: /etc/vault/tls/ca.crt
        - name: VAULT_ROLE
          value: agent-role
        image: vault
        name: vault-agent-auth
        resources: {}
        volumeMounts:
        - mountPath: /home/vault
          name: vault-token
        - mountPath: /etc/vault
          name: config
        - mountPath: /etc/vault/tls
          name: vault-tls
      - args:
        - -config=/etc/consul-template/consul-template-config.hcl
        - -log-level=debug
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: https://35.222.149.11:443
        - name: VAULT_CACERT
          value: /etc/vault/tls/ca.crt
        image: hashicorp/consul-template
        imagePullPolicy: Always
        name: consul-template
        resources: {}
        volumeMounts:
        - mountPath: /home/vault
          name: vault-token
        - mountPath: /etc/consul-template
          name: config
        - mountPath: /etc/secrets
          name: shared-data
        - mountPath: /etc/vault/tls
          name: vault-tls
      - image: gcr.io/searce-sandbox/abc:2d5d833-dirty-75ae930
        name: php-apache
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: shared-data
      serviceAccountName: vault-auth
      volumes:
      - emptyDir:
          medium: Memory
        name: vault-token
      - configMap:
          items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl
          - key: consul-template-config.hcl
            path: consul-template-config.hcl
          name: vault-agent-config-g9cmfhmgmh
        name: config
      - emptyDir: {}
        name: shared-data
      - name: vault-tls
        secret:
          secretName: vault-tls
